### ISSUE TITLE
passwords not working

### ISSUE THREAD

**Issue by photonclock** [davidnewhall/SecSpyCLI#2]
Try setting up a Security Spy user 'test' with password 'test1234' or try a password that requires escaped chars ie, 'p@ss=word'.

**Comment by davidnewhall** [comment]
I think I wrote somewhere that I've never actually tested this with authentication. 🗡 

I can work on that! Thanks for the report.

**Comment by photonclock** [comment]
>I've never actually tested this with authentication. 

Ah, sorry I didn't see that. So it's a feature request not a bug  ;-)

**Comment by davidnewhall** [comment]
I have quite a bit of cleanup to do around this app and the securityspy library. I'll try to get this ironed out soon.

**Comment by davidnewhall** [comment]
Alright, so the request is to allow special characters that `bash` would otherwise rip out? A password without special characters *is* working for you?

I really only wrote this app as a way to test the library I wrote. At some point later I made another project that makes it very easy to package a Golang application for Linux, Docker, Homebrew, etc, and I applied it here. That makes this app really easy to get/use, and now people are finding it. :D 

What solution would work for you? A config file? Setting the password via ENV variable? Honestly I'll probably do both. This isn't a new concept, but I just want to make sure your use case is covered since you're obviously finding a use for the app. Probably more so than me.

**Comment by davidnewhall** [comment]
I can't get it to work with a password at all. heh..

**Comment by davidnewhall** [comment]
You've found what looks like a bug in SecuritySpy. I opened a support request with Ben. I'll let you know what we figure out!

**Comment by photonclock** [comment]
Well I initially had a password that had some special chars in it like '@' and '='   those didn't work so I tried a password that was alphanumeric only plus some underscores. That didn't work. Finally I made a 'test' user in Security spy with password 'test' and that worked. Obviously not too secure though. ;-)  As long as alphanumeric/underscore works that would be fine. Is the SecSpy bug that it doesn't properly escape certain chars like @ = ?  As far as the fix on your end, can the password just be enclosed in quotes in the shell ie:   secspy -u userName -p "My1234_Password456" -U etc....  ?

This currently works:
secspy -u test -p test -U https://127.0.0.1:#### -c cams

**Comment by davidnewhall** [comment]
It's actually a bug in security spy. Ben released a beta version with a fix. Can you give that a try? I just tested it and it's working.

https://www.bensoftware.com/securityspy/download-beta.html

**Comment by davidnewhall** [comment]
Any chance you were able to give the new SecuritySpy a go? You don't have to upgrade your server, you can install a local version, point it at your server, then point `secspy` at that.

**Comment by photonclock** [comment]
Resolved! Thank you!

**Comment by davidnewhall** [comment]
Glad I found you on the forums and prodded you to come back :D
(I didn't realize it was the same person at first, haha)
